name: Structured Matrix data

on: push

jobs:

  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        run:
          - name: 'run1'
            sleep: 5
          - name: 'run2'
            sleep: 10
          - name: 'run3'
            sleep: 15

    steps:
    - run: echo Run ${{ matrix.run.name }}
    - run: date
    - run: sleep ${{ matrix.run.sleep }} # Sleep so that we can see a difference in timestamp on the last run
    - run: date
