name: Structured Matrix data

on: push

jobs:

  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        run:
          - name: 'run1'
          - name: 'run2'
          - name: 'run3'

    steps:
    - run: echo Run ${{ matrix.run.name }}
    - run: date
    - run: sleep 5 # Sleep so that we can see a difference in timestamp on the last run
    - run: date
